const resultF02C = [
  {
    "symbol": "F02C",
    "title1": "Warning: In this subclass, non-limiting references (in the sense of paragraph 39 of the Guide to the IPC) may still be displayed in the scheme."
  },
  {
    "symbol": "F02C 1/00",
    "title1": "Gas-turbine plants characterised by the use of hot gases or unheated pressurised gases, as the working fluid (by the use of combustion products  F02C 3/00,  F02C 5/00) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 1/02",
    "title1": "•the working fluid being an unheated pressurised gas 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 1/04",
    "title1": "•the working fluid being heated indirectly 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 1/05",
    "title1": "••characterised by the type or source of heat, e.g. using nuclear or solar energy 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 1/06",
    "title1": "•••using reheated exhaust gas (F02C 1/08 takes precedence) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 1/08",
    "title1": "••Semi-closed cycles 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 1/10",
    "title1": "••Closed cycles 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/00",
    "title1": "Gas-turbine plants characterised by the use of combustion products as the working fluid (generated by intermittent combustion  F02C 5/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/02",
    "title1": "•using exhaust-gas pressure in a pressure exchanger to compress combustion-air (pressure exchangers per se F04F 13/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/04",
    "title1": "•having a turbine driving a compressor (power transmission arrangements  F02C 7/36; control of working fluid flow  F02C 9/16) 52006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/045",
    "title1": "••having compressor and turbine passages in a single rotor (F02C 3/073 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/05",
    "title1": "•••the compressor and the turbine being of the radial flow type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/055",
    "title1": "••the compressor being of the positive-displacement type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/06",
    "title1": "••the compressor comprising only axial stages (F02C 3/10 takes precedence) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/067",
    "title1": "•••having counter-rotating rotors (F02C 3/073 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/073",
    "title1": "•••the compressor and turbine stages being concentric 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/08",
    "title1": "••the compressor comprising at least one radial stage (F02C 3/10 takes precedence) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/09",
    "title1": "•••of the centripetal type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/10",
    "title1": "••with another turbine driving an output shaft but not driving the compressor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/107",
    "title1": "••with two or more rotors connected by power transmission 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/113",
    "title1": "•••with variable power transmission between rotors 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/13",
    "title1": "••having variable working fluid interconnections between turbines or compressors or stages of different rotors 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/14",
    "title1": "•characterised by the arrangement of the combustion chamber in the plant (combustion chambers per se F23R) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/16",
    "title1": "••the combustion chambers being formed at least partly in the turbine rotor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/20",
    "title1": "•using a special fuel, oxidant, or dilution fluid to generate the combustion products 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/22",
    "title1": "••the fuel or oxidant being gaseous at standard temperature and pressure (F02C 3/28 takes precedence) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/24",
    "title1": "••the fuel or oxidant being liquid at standard temperature and pressure 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/26",
    "title1": "••the fuel or oxidant being solid or pulverulent, e.g. in slurry or suspension 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/28",
    "title1": "•••using a separate gas producer for gasifying the fuel before combustion 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/30",
    "title1": "••Adding water, steam or other fluids to the combustible ingredients or to the working fluid before discharge from the turbine (heating of air intakes to prevent icing  F02C 7/047) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/32",
    "title1": "•Inducing air flow by fluid jet, e.g. ejector action 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/34",
    "title1": "•with recycling of part of the working fluid, i.e. semi-closed cycles with combustion products in the closed part of the cycle 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 3/36",
    "title1": "•Open cycles 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 5/00",
    "title1": "Gas-turbine plants characterised by the working fluid being generated by intermittent combustion 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 5/02",
    "title1": "•characterised by the arrangement of the combustion chamber in the plant (combustion chambers per se F23R) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 5/04",
    "title1": "••the combustion chambers being formed at least partly in the turbine rotor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 5/06",
    "title1": "•the working fluid being generated in an internal-combustion gas generator of the positive-displacement type having essentially no mechanical power output (internal-combustion engines with prolonged expansion using exhaust gas turbines  F02B) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 5/08",
    "title1": "••the gas generator being of the free-piston type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 5/10",
    "title1": "•the working fluid forming a resonating or oscillating gas column, i.e. the combustion chambers having no positively actuated valves, e.g. using Helmholtz effect 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 5/11",
    "title1": "••using valveless combustion chambers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 5/12",
    "title1": "•the combustion chambers having inlet or outlet valves, e.g. Holzwarth gas-turbine plants 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/00",
    "title1": "Plural gas-turbine plants; Combinations of gas-turbine plants with other apparatus (aspects predominantly concerning such apparatus, see the relevant classes for the apparatus); Adaptations of gas-turbine plants for special use 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/02",
    "title1": "•Plural gas-turbine plants having a common power output 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/04",
    "title1": "•Gas-turbine plants providing heated or pressurised working fluid for other apparatus, e.g. without mechanical power output (F02C 6/18 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/06",
    "title1": "••providing compressed gas (F02C 6/10 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/08",
    "title1": "•••the gas being bled from the gas-turbine compressor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/10",
    "title1": "••supplying working fluid to a user, e.g. a chemical process, which returns working fluid to a turbine of the plant 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/12",
    "title1": "•••Turbochargers, i.e. plants for augmenting mechanical power output of internal-combustion piston engines by increase of charge pressure 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/14",
    "title1": "•Gas-turbine plants having means for storing energy, e.g. for meeting peak loads 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/16",
    "title1": "••for storing compressed air 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/18",
    "title1": "•using the waste heat of gas-turbine plants outside the plants themselves, e.g. gas-turbine power heat plants (using waste heat as source of energy for refrigeration plants  F25B 27/02) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 6/20",
    "title1": "•Adaptations of gas-turbine plants for driving vehicles 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/00",
    "title1": "Features, component parts, details or accessories, not provided for in, or of interest apart from, groups  F02C 1/00-F02C 6/00; Air intakes for jet-propulsion plants (controlling  F02C 9/00) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/04",
    "title1": "•Air intakes for gas-turbine plants or jet-propulsion plants 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/042",
    "title1": "••having variable geometry 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/045",
    "title1": "••having provisions for noise suppression 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/047",
    "title1": "••Heating to prevent icing 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/05",
    "title1": "••having provisions for obviating the penetration of damaging objects or particles 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/052",
    "title1": "•••with dust-separation devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/055",
    "title1": "•••with intake grids, screens or guards 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/057",
    "title1": "••Control or regulation (conjointly with fuel supply control  F02C 9/50, with nozzle area control  F02K 1/16) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/06",
    "title1": "•Arrangement of bearings (bearings  F16C); Lubricating (of engines in general  F01M) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/08",
    "title1": "•Heating air supply before combustion, e.g. by exhaust gases 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/10",
    "title1": "••by means of regenerative heat-exchangers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/105",
    "title1": "•••of the rotary type (rotary heat exchangers per se F28D) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/12",
    "title1": "•Cooling of plants (of component parts, see the relevant subclasses, e.g.  F01D; cooling of engines in general  F01P) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/14",
    "title1": "••of fluids in the plant 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/141",
    "title1": "•••of working fluid (F02C 3/30 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/143",
    "title1": "••••before or between the compressor stages 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/16",
    "title1": "••characterised by cooling medium 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/18",
    "title1": "•••the medium being gaseous, e.g. air 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/20",
    "title1": "•Mounting or supporting of plant; Accommodating heat expansion or creep 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/22",
    "title1": "•Fuel supply systems 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/224",
    "title1": "••Heating fuel before feeding to the burner 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/228",
    "title1": "••Dividing fuel between various burners 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/232",
    "title1": "••Fuel valves; Draining valves or systems (valves in general  F16K) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/236",
    "title1": "••Fuel delivery systems comprising two or more pumps 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/24",
    "title1": "•Heat or noise insulation (air intakes having provisions for noise suppression  F02C 7/045; turbine exhaust heads, chambers, or the like  F01D 25/30; silencing nozzles of jet-propulsion plants  F02K 1/00) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/25",
    "title1": "••Fire protection or prevention (in general  A62) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/26",
    "title1": "•Starting; Ignition 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/262",
    "title1": "••Restarting after flame-out 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/264",
    "title1": "••Ignition 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/266",
    "title1": "•••Electric (sparking plugs  H01T) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/268",
    "title1": "••Starting drives for the rotor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/27",
    "title1": "•••Fluid drives (turbine starters  F02C 7/277) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/272",
    "title1": "••••generated by cartridges 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/275",
    "title1": "•••Mechanical drives 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/277",
    "title1": "••••the starter being a turbine 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/28",
    "title1": "•Arrangement of seals 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/30",
    "title1": "•Preventing corrosion in gas-swept spaces 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/32",
    "title1": "•Arrangement, mounting, or driving, of auxiliaries 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 7/36",
    "title1": "•Power transmission between the different shafts of the gas-turbine plant, or between the gas-turbine plant and the power user (F02C 7/32 takes precedence; couplings for transmitting rotation  F16D; gearing in general  F16H) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/00",
    "title1": "Controlling gas-turbine plants; Controlling fuel supply in air-breathing jet-propulsion plants (controlling air intakes  F02C 7/057; controlling turbines  F01D; controlling compressors  F04D 27/00) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/16",
    "title1": "•Control of working fluid flow (F02C 9/48 takes precedence; control of air-intake flow  F02C 7/057) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/18",
    "title1": "••by bleeding, by-passing or acting on variable working fluid interconnections between turbines or compressors or their stages 52006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/20",
    "title1": "••by throttling; by adjusting vanes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/22",
    "title1": "•••by adjusting turbine vanes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/24",
    "title1": "••Control of the pressure level in closed cycles 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/26",
    "title1": "•Control of fuel supply (F02C 9/48 takes precedence; fuel valves  F02C 7/232) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/28",
    "title1": "••Regulating systems responsive to plant or ambient parameters, e.g. temperature, pressure, rotor speed (F02C 9/30-F02C 9/38,  F02C 9/44 take precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/30",
    "title1": "••characterised by variable fuel pump output 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/32",
    "title1": "••characterised by throttling of fuel (F02C 9/38 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/34",
    "title1": "•••Joint control of separate flows to main and auxiliary burners 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/36",
    "title1": "••characterised by returning of fuel to sump (F02C 9/38 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/38",
    "title1": "••characterised by throttling and returning of fuel to sump 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/40",
    "title1": "••specially adapted to the use of a special fuel or a plurality of fuels 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/42",
    "title1": "••specially adapted for the control of two or more plants simultaneously 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/44",
    "title1": "••responsive to the speed of aircraft, e.g. Mach number control, optimisation of fuel consumption 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/46",
    "title1": "••Emergency fuel control 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/48",
    "title1": "•Control of fuel supply conjointly with another control of the plant (with nozzle section control  F02K 1/17) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/50",
    "title1": "••with control of working fluid flow 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/52",
    "title1": "•••by bleeding or by-passing the working fluid 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/54",
    "title1": "•••by throttling the working fluid, by adjusting vanes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/56",
    "title1": "••with power transmission control 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02C 9/58",
    "title1": "•••with control of a variable-pitch propeller 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
];