const resultF02P = [
  {
    "symbol": "F02P",
    "title1": "Warning: In this subclass, non-limiting references (in the sense of paragraph 39 of the Guide to the IPC) may still be displayed in the scheme."
  },
  {
    "symbol": "F02P 1/00",
    "title1": "Installations having electric ignition energy generated by magneto- or dynamo-electric generators without subsequent storage 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 1/02",
    "title1": "•the generator rotor being characterised by forming part of the engine flywheel 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 1/04",
    "title1": "•the generator being specially adapted for use with specific engine types, e.g. engines with V-arrangement of cylinders 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 1/06",
    "title1": "•Generator drives, e.g. having snap couplings 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 1/08",
    "title1": "•Layout of circuits 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/00",
    "title1": "Other electric spark ignition installations characterised by the type of ignition power generation storage 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/01",
    "title1": "•Electric spark ignition installations without subsequent energy storage, i.e. energy supplied by an electrical oscillator (with magneto- or dynamo-electric generators  F02P 1/00; piezo-electric ignition  F02P 3/12; with continuous electric spark  F02P 15/10) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/02",
    "title1": "•having inductive energy storage, e.g. arrangements of induction coils 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/04",
    "title1": "••Layout of circuits 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/045",
    "title1": "•••for control of the dwell or anti-dwell time 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/05",
    "title1": "•••for control of the magnitude of the current in the ignition coil (during starting  F02P 15/12) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/055",
    "title1": "•••with protective means to prevent damage to the circuit or the ignition coil 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/06",
    "title1": "•having capacitive energy storage (piezo-electric or electrostatic ignition  F02P 3/12) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/08",
    "title1": "••Layout of circuits (for low tension  F02P 3/10) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/09",
    "title1": "•••for control of the charging current in the capacitor (F02P 15/12 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/10",
    "title1": "••Low-tension installation, e.g. using surface-discharge sparking plugs 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 3/12",
    "title1": "•Piezoelectric ignition; Electrostatic ignition 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/00",
    "title1": "Advancing or retarding electric ignition spark; Control therefor 62006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/02",
    "title1": "•non-automatically; dependent on position of personal controls of engine, e.g. throttle position 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/04",
    "title1": "•automatically, as a function of the working conditions of the engine or vehicle or of the atmospheric conditions (dependent on position of personal controls of engine  F02P 5/02) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/05",
    "title1": "••using mechanical means 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/06",
    "title1": "•••dependent on engine speed 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/07",
    "title1": "••••Centrifugal timing mechanisms 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/10",
    "title1": "•••dependent on fluid pressure in engine, e.g. combustion-air pressure 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/12",
    "title1": "••••dependent on a specific pressure other than that of combustion-air, e.g. of exhaust, cooling fluid, lubricant 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/14",
    "title1": "•••dependent on specific conditions other than engine speed or engine fluid pressure, e.g. temperature 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/145",
    "title1": "••using electrical means 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/15",
    "title1": "•••Digital data processing 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/152",
    "title1": "••••dependent on pinking (detecting or indicating knocks in internal-combustion engines  G01L 23/22) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/153",
    "title1": "••••dependent on combustion pressure 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/155",
    "title1": "•••Analogue data processing 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 5/16",
    "title1": "•characterised by the mechanical transmission between sensing elements or personal controls and final actuating elements 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/00",
    "title1": "Arrangement of distributors, circuit-makers, circuit-breakers or pick-up devices for electric spark ignition (advancing or retarding ignition or control therefor  F02P 5/00; such devices per se, see the relevant classes of section H, e.g. rotary switches  H01H 19/00, contact-breakers, distributors  H01R 39/00, generators  H02K) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/02",
    "title1": "•of distributors 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/03",
    "title1": "••with electrical means (ignition occurring simultaneously at different places in one engine cylinder or in two or more separate engine cylinders  F02P 15/08) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/04",
    "title1": "••having distributors with air-tight casing 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/06",
    "title1": "•of circuit-makers or -breakers, or pick-up devices adapted to sense particular points of the timing cycle 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/063",
    "title1": "••Mechanical pick-up devices, circuit-makers or -breakers, e.g. contact-breakers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/067",
    "title1": "••Electromagnetic pick-up devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/07",
    "title1": "•••Hall-effect pick-up devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/073",
    "title1": "••Optical pick-up devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/077",
    "title1": "••Circuits therefor, e.g. pulse generators 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/08",
    "title1": "••having air-tight casings 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 7/10",
    "title1": "•Drives of distributors or of circuit-makers or -breakers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 9/00",
    "title1": "Electric spark ignition control, not otherwise provided for 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 11/00",
    "title1": "Safety means for electric spark ignition, not otherwise provided for 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 11/02",
    "title1": "•Preventing damage to engines or engine-driven gearing 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 11/04",
    "title1": "•Preventing unauthorised use of engines (of vehicles  B60R 25/04; ignition locks  H01H 27/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 11/06",
    "title1": "•Indicating unsafe conditions 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 13/00",
    "title1": "Sparking plugs structurally combined with other parts of internal-combustion engines (with fuel injectors  F02M 57/06; predominant aspects of the parts, see the relevant subclasses) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 15/00",
    "title1": "Electric spark ignition having characteristics not provided for in, or of interest apart from, groups  F02P 1/00-F02P 13/00 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 15/02",
    "title1": "•Arrangements having two or more sparking plugs 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 15/04",
    "title1": "•one of the spark electrodes being mounted on the engine working piston 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 15/06",
    "title1": "•the electric spark triggered by engine working cylinder compression 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 15/08",
    "title1": "•having multiple-spark ignition, i.e. ignition occurring simultaneously at different places in one engine cylinder or in two or more separate engine cylinders 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 15/10",
    "title1": "•having continuous electric sparks 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 15/12",
    "title1": "•having means for strengthening spark during starting 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 17/00",
    "title1": "Testing of ignition installations, e.g. in combination with adjusting (testing fuel injection apparatus  F02M 65/00; testing ignition installations in general  F23Q 23/00); Testing of ignition timing in compression-ignition engines 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 17/02",
    "title1": "•Checking or adjusting ignition timing 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 17/04",
    "title1": "••dynamically 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 17/06",
    "title1": "•••using a stroboscopic lamp 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 17/08",
    "title1": "•••using a cathode-ray oscilloscope (F02P 17/06 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 17/10",
    "title1": "•Measuring dwell or antidwell time 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 17/12",
    "title1": "•Testing characteristics of the spark, ignition voltage or current 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 19/00",
    "title1": "Incandescent ignition, e.g. during starting of internal-combustion engines; Combination of incandescent and spark ignition 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 19/02",
    "title1": "•electric, e.g. layout of circuits of apparatus having glowing plugs 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 19/04",
    "title1": "•non-electric, e.g. heating incandescent spots by burners (use of burners for direct ignition  F02P 21/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 21/00",
    "title1": "Direct use of flames or burners for ignition 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 21/02",
    "title1": "•the flames being kept burning essentially external to engine working chambers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 21/04",
    "title1": "•Burning-cartridges or like inserts being arranged in engine working chambers (as starting aid  F02N 19/02) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 23/00",
    "title1": "Other ignition 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F02P 23/02",
    "title1": "•Friction, pyrophoric, or catalytic ignition 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
]; {
    "symbol": "F02P 23/04",
    "title1": "•Other physical ignition means, e.g. using laser rays 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
];