const resultH05H = [
  {
    "symbol": "H05H",
    "title1": "Warning: In this subclass, non-limiting references (in the sense of paragraph 39 of the Guide to the IPC) may still be displayed in the scheme."
  },
  {
    "symbol": "H05H 1/00",
    "title1": "Generating plasma; Handling plasma (application of plasma technique in thermonuclear fusion reactors  G21B 1/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/02",
    "title1": "•Arrangements for confining plasma by electric or magnetic fields; Arrangements for heating plasma (electron optics  H01J) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/03",
    "title1": "••using electrostatic fields 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/04",
    "title1": "••using magnetic fields substantially generated by the discharge in the plasma 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/06",
    "title1": "•••Longitudinal pinch devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/08",
    "title1": "•••Theta pinch devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/10",
    "title1": "••using applied magnetic fields only 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/11",
    "title1": "•••using cusp configuration (H05H 1/14 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/12",
    "title1": "•••wherein the containment vessel forms a closed loop, e.g. stellarator 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/14",
    "title1": "•••wherein the containment vessel is straight and has magnetic mirrors 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/16",
    "title1": "••using applied electric and magnetic fields 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/18",
    "title1": "•••wherein the fields oscillate at a very high frequency, e.g. in the microwave range 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/20",
    "title1": "••Ohmic heating 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/22",
    "title1": "••for injection heating 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/24",
    "title1": "•Generating plasma 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/26",
    "title1": "••Plasma torches 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/28",
    "title1": "•••Cooling arrangements 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/30",
    "title1": "•••using applied electromagnetic fields, e.g. high-frequency or microwave energy (H05H 1/28 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/32",
    "title1": "•••using an arc (H05H 1/28 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/34",
    "title1": "••••Details, e.g. electrodes, nozzles 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/36",
    "title1": "•••••Circuit arrangements (H05H 1/38,  H05H 1/40 take precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/38",
    "title1": "•••••Guiding or centering of electrodes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/40",
    "title1": "•••••using applied magnetic fields, e.g. for focusing or rotating the arc 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/42",
    "title1": "••••with provisions for introducing materials into the plasma, e.g. powder, liquid (electrostatic spraying, spraying apparatus with means for charging the spray electrically  B05B 5/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/44",
    "title1": "••••using more than one torch 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/46",
    "title1": "••using applied electromagnetic fields, e.g. high frequency or microwave energy (H05H 1/26 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/48",
    "title1": "••using an arc (H05H 1/26 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/50",
    "title1": "•••and using applied magnetic fields, e.g. for focusing or rotating the arc 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/52",
    "title1": "••using exploding wires or spark gaps (H05H 1/26 takes precedence; spark gaps in general  H01T) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 1/54",
    "title1": "•Plasma accelerators 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 3/00",
    "title1": "Production or acceleration of neutral particle beams, e.g. molecular or atomic beams 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 3/02",
    "title1": "•Molecular or atomic-beam generation, e.g. resonant beam generation (gas masers  H01S 1/06) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 3/04",
    "title1": "•Acceleration by electromagnetic wave pressure 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 3/06",
    "title1": "•Generating neutron beams (targets for producing nuclear reactions  H05H 6/00; neutron sources  G21G 4/02) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 5/00",
    "title1": "Direct voltage accelerators; Accelerators using single pulses (H05H 3/06 takes precedence) 52006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 5/02",
    "title1": "•Details (targets for producing nuclear reactions  H05H 6/00) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 5/03",
    "title1": "••Accelerating tubes (vessels or containers of electric discharge tubes with improved potential distribution over surface of vessel  H01J 5/06; shields of X-ray tubes associated with vessels or containers  H01J 35/16) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 5/04",
    "title1": "•energised by electrostatic generators, e.g. by van de Graaff generator 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 5/06",
    "title1": "•Tandem accelerators; Multi-stage accelerators 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 5/08",
    "title1": "•Particle accelerators using step-up transformers, e.g. resonance transformers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 6/00",
    "title1": "Targets for producing nuclear reactions (supports for targets or objects to be irradiated  G21K 5/08) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/00",
    "title1": "Details of devices of the types covered by groups  H05H 9/00-H05H 13/00 (targets for producing nuclear reactions  H05H 6/00) 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/02",
    "title1": "•Circuits or systems for supplying or feeding radio-frequency energy (radio-frequency generators  H03B) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/04",
    "title1": "•Magnet systems; Energisation thereof 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/06",
    "title1": "•Two-beam arrangements; Multi-beam arrangements 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/08",
    "title1": "•Arrangements for injecting particles into orbits 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/10",
    "title1": "•Arrangements for ejecting particles from orbits 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/12",
    "title1": "•Arrangements for varying final energy of beam 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/14",
    "title1": "•Vacuum chambers (H05H 5/03 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/16",
    "title1": "••of the waveguide type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/18",
    "title1": "••Cavities; Resonators 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/20",
    "title1": "•••with superconductive walls 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 7/22",
    "title1": "•Details of linear accelerators, e.g. drift tubes (H05H 7/02-H05H 7/20 take precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 9/00",
    "title1": "Linear accelerators (H05H 11/00 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 9/02",
    "title1": "•Travelling-wave linear accelerators 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
]; {
    "symbol": "H05H 9/04",
    "title1": "•Standing-wave linear accelerators 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 11/00",
    "title1": "Magnetic induction accelerators, e.g. betatrons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 11/02",
    "title1": "•Air-cored betatrons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 11/04",
    "title1": "•Biased betatrons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 13/00",
    "title1": "Magnetic resonance accelerators; Cyclotrons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 13/02",
    "title1": "•Synchrocyclotrons, i.e. frequency-modulated cyclotrons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 13/04",
    "title1": "•Synchrotrons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 13/06",
    "title1": "•Air-cored magnetic resonance accelerators 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 13/08",
    "title1": "•Alternating-gradient magnetic resonance accelerators 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 13/10",
    "title1": "•Accelerators comprising one or more linear accelerating sections and bending magnets or the like to return the charged particles in a trajectory parallel to the first accelerating section, e.g. microtrons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "H05H 15/00",
    "title1": "Methods or devices for acceleration of charged particles not otherwise provided for 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
];