const resultH03F = [
  {
    symbol: "H03F",
    title1:
      "Warning: In this subclass, non-limiting references (in the sense of paragraph 39 of the Guide to the IPC) may still be displayed in the scheme.",
  },
  {
    symbol: "H03F 1/00",
    title1:
      'Details of amplifiers with only discharge tubes, only semiconductor devices or only unspecified devices as amplifying elements 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/02",
    title1:
      '•Modifications of amplifiers to raise the efficiency, e.g. gliding Class A stages, use of an auxiliary oscillation 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/04",
    title1:
      '••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/06",
    title1:
      '•••to raise the efficiency of amplifying modulated radio frequency waves; to raise the efficiency of amplifiers acting also as modulators 22006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/07",
    title1:
      '••••Doherty-type amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/08",
    title1:
      '•Modifications of amplifiers to reduce detrimental influences of internal impedances of amplifying elements (wide-band amplifiers with inter-stage coupling networks incorporating these impedances  H03F 1/42; eliminating transit-time effects in vacuum tubes  H01J 21/34) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/10",
    title1:
      '••by use of amplifying elements with multiple electrode connections 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/12",
    title1:
      '••by use of attenuating means 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/13",
    title1:
      '•••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/14",
    title1:
      '••by use of neutralising means 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/16",
    title1:
      '•••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/18",
    title1:
      '••by use of distributed coupling 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/20",
    title1:
      '•••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/22",
    title1:
      '••by use of cascode coupling, i.e. earthed cathode or emitter stage followed by earthed grid or base stage respectively 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/24",
    title1:
      '•••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/26",
    title1:
      '•Modifications of amplifiers to reduce influence of noise generated by amplifying elements 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/28",
    title1:
      '••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/30",
    title1:
      '•Modifications of amplifiers to reduce influence of variations of temperature or supply voltage 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/32",
    title1:
      '•Modifications of amplifiers to reduce non-linear distortion (by negative feedback  H03F 1/34) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/33",
    title1:
      '••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/34",
    title1:
      '•Negative-feedback-circuit arrangements with or without positive feedback (H03F 1/02-H03F 1/30,  H03F 1/38-H03F 1/50,  H03F 3/50 take precedence) 32006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/36",
    title1:
      '••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/38",
    title1:
      '•Positive-feedback circuit arrangements without negative feedback 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/40",
    title1:
      '••in discharge-tube amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/42",
    title1:
      '•Modifications of amplifiers to extend the bandwidth 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/44",
    title1:
      '••of tuned amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/46",
    title1:
      '•••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/48",
    title1:
      '••of aperiodic amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/50",
    title1:
      '•••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/52",
    title1:
      '•Circuit arrangements for protecting such amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/54",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 1/56",
    title1:
      '•Modifications of input or output impedances, not otherwise provided for 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/00",
    title1:
      'Amplifiers with only discharge tubes or only semiconductor devices as amplifying elements 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/02",
    title1:
      '•with tubes only (subsequent subgroups take precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/04",
    title1:
      '•with semiconductor devices only (subsequent subgroups take precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/06",
    title1:
      '••using hole storage effect 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/08",
    title1:
      '••controlled by light 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/10",
    title1:
      '••with diodes 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/12",
    title1:
      '•••with Esaki diodes 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/14",
    title1:
      '••with amplifying devices having more than three electrodes or more than two PN junctions 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/16",
    title1:
      '••with field-effect devices 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/18",
    title1:
      '•with semiconductor devices of complementary types (subsequent subgroups take precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/181",
    title1:
      '•Low-frequency amplifiers, e.g. audio preamplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/183",
    title1:
      '••with semiconductor devices only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/185",
    title1:
      '•••with field-effect devices (H03F 3/187 takes precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/187",
    title1:
      '•••in integrated circuits 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/189",
    title1:
      '•High-frequency amplifiers, e.g. radio frequency amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/19",
    title1:
      '••with semiconductor devices only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/191",
    title1:
      '•••Tuned amplifiers (H03F 3/193,  H03F 3/195 take precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/193",
    title1:
      '•••with field-effect devices (H03F 3/195 takes precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/195",
    title1:
      '•••in integrated circuits 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/20",
    title1:
      '•Power amplifiers, e.g. Class B amplifiers, Class C amplifiers (H03F 3/26-H03F 3/30 take precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/21",
    title1:
      '••with semiconductor devices only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/213",
    title1:
      '•••in integrated circuits 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/217",
    title1:
      '•••Class D power amplifiers; Switching amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/22",
    title1:
      '••with tubes only (H03F 3/24 takes precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/24",
    title1:
      '••of transmitter output stages 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/26",
    title1:
      '•Push-pull amplifiers; Phase-splitters therefor (duplicated single-ended push-pull arrangements or phase-splitters therefor  H03F 3/30) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/28",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/30",
    title1:
      '•Single-ended push-pull amplifiers; Phase-splitters therefor 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/32",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/34",
    title1:
      '•Dc amplifiers in which all stages are dc-coupled (H03F 3/45 takes precedence) 32006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/343",
    title1:
      '••with semiconductor devices only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/345",
    title1:
      '•••with field-effect devices (H03F 3/347 takes precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/347",
    title1:
      '•••in integrated circuits 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/36",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/38",
    title1:
      '•Dc amplifiers with modulator at input and demodulator at output; Modulators or demodulators specially adapted for use in such amplifiers (modulators in general  H03C; demodulators in general  H03D; amplitude modulation of pulses in general  H03K 7/02; amplitude demodulation of pulses in general  H03K 9/02) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/387",
    title1:
      '••with semiconductor devices only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/393",
    title1:
      '•••with field-effect devices 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/40",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/42",
    title1:
      '•Amplifiers with two or more amplifying elements having their dc paths in series with the load, the control electrode of each element being excited by at least part of the input signal, e.g. so-called totem-pole amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/44",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/45",
    title1:
      '•Differential amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/46",
    title1:
      '•Reflex amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/48",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/50",
    title1:
      '•Amplifiers in which input is applied to, or output is derived from, an impedance common to input and output circuits of the amplifying element, e.g. cathode follower 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/52",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/54",
    title1:
      '•Amplifiers using transit-time effect in tubes or semiconductor devices (parametric amplifiers  H03F 7/00; solid state travelling-wave devices  H10N 70/10) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/55",
    title1:
      '••with semiconductor devices only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/56",
    title1:
      '••using klystrons 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/58",
    title1:
      '••using travelling-wave tubes 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/60",
    title1:
      '•Amplifiers in which coupling networks have distributed constants, e.g. with waveguide resonators (H03F 3/54 takes precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/62",
    title1:
      '•Two-way amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/64",
    title1:
      '••with tubes only 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/66",
    title1:
      '•Amplifiers simultaneously generating oscillations of one frequency and amplifying signals of another frequency 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/68",
    title1:
      '•Combinations of amplifiers, e.g. multi-channel amplifiers for stereophonics 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/70",
    title1:
      '•Charge amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 3/72",
    title1:
      '•Gated amplifiers, i.e. amplifiers which are rendered operative or inoperative by means of a control signal 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 5/00",
    title1:
      'Amplifiers with both discharge tubes and semiconductor devices as amplifying elements 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 7/00",
    title1:
      'Parametric amplifiers (devices or arrangements for the parametric generation or amplification of light, infra-red or ultra-violet waves  G02F 1/39) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 7/02",
    title1:
      '•using variable-inductance element; using variable-permeability element 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 7/04",
    title1:
      '•using variable-capacitance element; using variable-permitivity element 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 7/06",
    title1:
      '•with electron beam tube 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 9/00",
    title1:
      'Magnetic amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 9/02",
    title1:
      '•current-controlled, i.e. the load current flowing in both directions through a main coil 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 9/04",
    title1:
      '•voltage-controlled, i.e. the load current flowing in only one direction through a main coil, e.g. Logan circuits (H03F 9/06 takes precedence) 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 9/06",
    title1:
      '•Control by voltage time integral, i.e. the load current flowing in only one direction through a main coil, whereby the main coil winding also can be used as a control winding, e.g. Ramey circuits 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 11/00",
    title1:
      'Dielectric amplifiers 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 13/00",
    title1:
      'Amplifiers using amplifying element consisting of two mechanically- or acoustically-coupled transducers, e.g. telephone-microphone amplifier 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 15/00",
    title1:
      'Amplifiers using galvano-magnetic effects not involving mechanical movement, e.g. using Hall effect 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 17/00",
    title1:
      'Amplifiers using electroluminescent element or photocell 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 19/00",
    title1:
      'Amplifiers using superconductivity effects 2006.01" href="#" oncontextmenu="return false;" onclick="return false;">[2006.01]',
  },
  {
    symbol: "H03F 99/00",
    title1:
      "Subject matter not provided for in other groups of this subclass [2009.01]",
  },
];
