const resultF22G = [
  {
    "symbol": "F22G",
    "title1": "Warning: In this subclass, non-limiting references (in the sense of paragraph 39 of the Guide to the IPC) may still be displayed in the scheme."
  },
  {
    "symbol": "F22G",
    "title1": "Definitions"
  },
  {
    "symbol": "F22G 1/00",
    "title1": "Steam superheating characterised by heating method (exothermal chemical reactions not involving a supply of free oxygen gas, apparatus or devices for using the heat therefrom  F24V 30/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 1/02",
    "title1": "•with heat supply by hot flue gases from the furnace of the steam boiler 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 1/04",
    "title1": "••by diverting flow or hot flue gases to separate superheaters operating in reheating cycle, e.g. for reheating steam between a high-pressure turbine stage and an intermediate turbine stage 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 1/06",
    "title1": "•with heat supply predominantly by radiation 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 1/08",
    "title1": "••from heated brickwork or the like 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 1/10",
    "title1": "•with provision for superheating by throttling 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 1/12",
    "title1": "•by mixing steam with furnace gases or other combustion products 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 1/14",
    "title1": "•using heat generated by chemical reactions 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 1/16",
    "title1": "•by using a separate heat source independent from heat supply of the steam boiler, e.g. by electricity, by auxiliary combustion of fuel oil 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 3/00",
    "title1": "Steam superheaters characterised by constructional features; Details or component parts thereof (general aspects of enclosed heat-exchangers  F28D) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/00",
    "title1": "Controlling superheat temperature (control systems for steam boilers  F22B; regulating or controlling in general  G05) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/02",
    "title1": "•Applications of combustion-control devices, e.g. tangential-firing burners, tilting burners 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/04",
    "title1": "•by regulating flue gas flow, e.g. by proportioning or diverting 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/06",
    "title1": "•by recirculating flue gases 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/08",
    "title1": "••preventing furnace gas backflow through recirculating fan 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/10",
    "title1": "•by displacing superheater sections 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/12",
    "title1": "•by attemperating the superheated steam, e.g. by injected water sprays (spray-mixers  B01F 25/70) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/14",
    "title1": "••by live steam 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/16",
    "title1": "•by indirectly cooling or heating the superheated steam in auxiliary enclosed heat-exchanger 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
]; {
    "symbol": "F22G 5/18",
    "title1": "•by by-passing steam around superheater sections 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 5/20",
    "title1": "•by combined controlling procedures 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 7/00",
    "title1": "Steam superheaters characterised by location, arrangement, or disposition 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 7/02",
    "title1": "•in fire tubes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 7/04",
    "title1": "•in jackets around fire tubes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 7/06",
    "title1": "•in furnace tubes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 7/08",
    "title1": "•in fire-boxes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 7/10",
    "title1": "•in smoke-boxes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 7/12",
    "title1": "•in flues 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F22G 7/14",
    "title1": "•in water-tube boilers, e.g. between banks of water tubes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
];