const resultF04F = [
  {
    "symbol": "F04F",
    "title1": "Warning: In this subclass, non-limiting references (in the sense of paragraph 39 of the Guide to the IPC) may still be displayed in the scheme."
  },
  {
    "symbol": "F04F 1/00",
    "title1": "Pumps using positively or negatively pressurised fluid medium acting directly on the liquid to be pumped (using only negative pressure  F04F 3/00; jet pumps  F04F 5/00; siphons  F04F 10/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/02",
    "title1": "•using both positively and negatively pressurised fluid medium, e.g. alternating 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/04",
    "title1": "••generated by vaporising and condensing 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/06",
    "title1": "•the fluid medium acting on the surface of the liquid to be pumped (F04F 1/02 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/08",
    "title1": "••specially adapted for raising liquids from great depths, e.g. in wells 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/10",
    "title1": "••of multiple type, e.g. with two or more units in parallel (F04F 1/08 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/12",
    "title1": "•••in series 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/14",
    "title1": "••adapted to pump specific liquids, e.g. corrosive or hot liquids 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/16",
    "title1": "••characterised by the fluid medium being suddenly pressurised, e.g. by explosion 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/18",
    "title1": "•the fluid medium being mixed with, or generated from, the liquid to be pumped 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 1/20",
    "title1": "••specially adapted for raising liquids from great depths, e.g. in wells 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 3/00",
    "title1": "Pumps using negative pressure acting directly on the liquid to be pumped (siphons  F04F 10/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/00",
    "title1": "Jet pumps, i.e. devices in which fluid flow is induced by pressure drop caused by velocity of another fluid flow (diffusion pumps  F04F 9/00; combination of jet pumps with pumps of other than jet type  F04B; use of jet pumps for priming or boosting non-positive-displacement pumps  F04D) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/02",
    "title1": "•the inducing fluid being liquid 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/04",
    "title1": "••displacing elastic fluids 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/06",
    "title1": "•••of rotary type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/08",
    "title1": "•••the elastic fluid being entrained in a free-falling column of liquid 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/10",
    "title1": "••displacing liquids, e.g. containing solids, or liquids and elastic fluids 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/12",
    "title1": "•••of multi-stage type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/14",
    "title1": "•the inducing fluid being elastic fluid 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/16",
    "title1": "••displacing elastic fluids 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/18",
    "title1": "•••for compressing 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/20",
    "title1": "•••for evacuating 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/22",
    "title1": "••••of multi-stage type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/24",
    "title1": "••displacing liquids, e.g. containing solids, or liquids and elastic fluids 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/26",
    "title1": "•••of multi-stage type (F04F 5/28 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/28",
    "title1": "•••Restarting of inducing action 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/30",
    "title1": "••••with axially-slidable combining nozzle 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/32",
    "title1": "••••with hinged flap in combining nozzle 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/34",
    "title1": "••characterised by means for changing inducing-fluid source 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/36",
    "title1": "••characterised by using specific inducing fluid 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/38",
    "title1": "•••the inducing fluid being mercury vapour 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/40",
    "title1": "•••the inducing fluid being oil vapour 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/42",
    "title1": "•characterised by the input flow of inducing fluid medium being radial or tangential to output flow (cyclones  B04C) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/44",
    "title1": "•Component parts, details, or accessories not provided for in, or of interest apart from, groups  F04F 5/02-F04F 5/42 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/46",
    "title1": "••Arrangements of nozzles 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/48",
    "title1": "••Control 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/50",
    "title1": "•••of compressing pumps 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/52",
    "title1": "•••of evacuating pumps 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 5/54",
    "title1": "•Installations characterised by use of jet pumps, e.g. combinations of two or more jet pumps of different type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 7/00",
    "title1": "Pumps displacing fluids by using inertia thereof, e.g. by generating vibrations therein 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 7/02",
    "title1": "•Hydraulic rams 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 9/00",
    "title1": "Diffusion pumps 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 9/02",
    "title1": "•of multi-stage type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 9/04",
    "title1": "•in combination with fore pumps, e.g. use of isolating valves 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 9/06",
    "title1": "•Arrangement of vapour traps 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 9/08",
    "title1": "•Control 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 10/00",
    "title1": "Siphons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 10/02",
    "title1": "•Gravity-actuated siphons 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "F04F 13/00",
    "title1": "Pressure exchangers [2009.01]"
  }
]; {
    "symbol": "F04F 99/00",
    "title1": "Subject matter not provided for in other groups of this subclass [2009.01]"
  }
];