const resultB03B = [
  {
    "symbol": "B03B",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 1/00",
    "title1": "Conditioning for facilitating separation by altering physical properties of the matter to be treated 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 1/00",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 1/02",
    "title1": "•Preparatory heating 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 1/04",
    "title1": "•by additives 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 1/06",
    "title1": "•by varying ambient atmospheric pressure 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 4/00",
    "title1": "Separating by pneumatic tables or by pneumatic jigs 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 4/00",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 4/02",
    "title1": "•using swinging or shaking tables 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 4/04",
    "title1": "•using rotary tables or tables formed by travelling belts 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 4/04",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 4/06",
    "title1": "•using fixed and inclined tables 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/00",
    "title1": "Washing granular, powdered or lumpy materials; Wet separating (separating by pneumatic tables or by pneumatic jigs  B03B 4/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/02",
    "title1": "•using shaken, pulsated or stirred beds as the principal means of separation (B03B 5/28,  B03B 5/48 take precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/04",
    "title1": "••on shaking tables (on vanners  B03B 5/08) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/06",
    "title1": "•••Constructional details of shaking tables, e.g. riffling 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/08",
    "title1": "••on vanners 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/10",
    "title1": "••on jigs 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/12",
    "title1": "•••using pulses generated mechanically in fluid 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/14",
    "title1": "••••Plunger jigs 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/16",
    "title1": "••••Diaphragm jigs 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/18",
    "title1": "••••Moving-sieve jigs 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/20",
    "title1": "•••using pulses generated by air injection 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/22",
    "title1": "•••using pulses generated by liquid injection 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/24",
    "title1": "•••Constructional details of jigs, e.g. pulse control devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/26",
    "title1": "••in sluices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/28",
    "title1": "•by sink-float separation 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/30",
    "title1": "••using heavy liquids or suspensions 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/32",
    "title1": "•••using centrifugal force 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/32",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 5/34",
    "title1": "••••Applications of hydrocyclones 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/36",
    "title1": "•••Devices therefor, other than using centrifugal force 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/36",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 5/38",
    "title1": "••••of conical receptacle type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/40",
    "title1": "••••of trough type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/42",
    "title1": "••••of drum or lifting wheel type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/44",
    "title1": "•••Application of particular media therefor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/46",
    "title1": "••using dry heavy media; Devices therefor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/48",
    "title1": "•by mechanical classifiers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/48",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 5/50",
    "title1": "••Rake classifiers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/52",
    "title1": "••Spiral classifiers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/54",
    "title1": "••Drag classifiers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/56",
    "title1": "••Drum classifiers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/58",
    "title1": "••Bowl classifiers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/60",
    "title1": "•by non-mechanical classifiers, e.g. slime tanks (hydraulic classifiers  B03B 5/62; water impulse classifiers  B03B 5/68) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/60",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 5/62",
    "title1": "•by hydraulic classifiers, e.g. of launder, tank, spiral or helical chute concentrator type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/64",
    "title1": "••of the free settling type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/66",
    "title1": "••of the hindered settling type 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/68",
    "title1": "•by water impulse (hydraulic classifiers  B03B 5/62) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/68",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 5/70",
    "title1": "••on tables or strakes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/72",
    "title1": "•••which are movable 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 5/74",
    "title1": "••••Revolving tables 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
]; {
    "symbol": "B03B 7/00",
    "title1": "Combinations of wet processes or apparatus with other processes or apparatus, e.g. for dressing ores or garbage 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 9/00",
    "title1": "General arrangement of separating plant, e.g. flow sheets 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 9/02",
    "title1": "•specially adapted for oil-sand, oil-chalk, oil-shales, ozokerite, bitumen, or the like 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
]; {
    "symbol": "B03B 9/04",
    "title1": "•specially adapted for furnace residues, smeltings, or foundry slags 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 9/06",
    "title1": "•specially adapted for refuse 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 11/00",
    "title1": "Feed or discharge devices integral with washing or wet-separating equipment 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 11/00",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 13/00",
    "title1": "Control arrangements specially adapted for wet- separating apparatus or for dressing plant, using physical effects 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 13/00",
    "title1": "Definitions"
  },
  {
    "symbol": "B03B 13/02",
    "title1": "•using optical effects 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 13/04",
    "title1": "•using electrical or electromagnetic effects 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B03B 13/06",
    "title1": "•using absorption or reflection of radioactive emanation 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
];