const resultB25D = [
  {
    "symbol": "B25D",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 1/00",
    "title1": "Hand hammers; Hammer heads of special shape or materials 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 1/02",
    "title1": "•Inserts or attachments forming the striking part of hammer heads (B25D 1/08-B25D 1/14 take precedence) 52006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 1/04",
    "title1": "•with provision for withdrawing or holding nails or spikes 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 1/06",
    "title1": "••Magnetic holders 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 1/08",
    "title1": "•having deformable heads (B25D 1/12 takes precedence) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 1/10",
    "title1": "•having work protector surrounding faces 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 1/12",
    "title1": "•having shock-absorbing means 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 1/14",
    "title1": "•having plural striking faces 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 1/16",
    "title1": "•having the impacting head in the form of a sleeve slidable on a shaft, e.g. hammers for driving a valve or draw-off tube into a barrel 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 3/00",
    "title1": "Hand chisels (mortise chisels  B27G 17/08) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 5/00",
    "title1": "Centre punches 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 5/02",
    "title1": "•Automatic centre punches 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 7/00",
    "title1": "Picks 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 7/00",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 9/00",
    "title1": "Portable percussive tools with fluid-pressure drive, e.g. having several percussive tool bits operated simultaneously (centrifugal or rotary impact type  B25D 15/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/00",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 9/02",
    "title1": "•of the tool-carrier piston type, i.e. in which the tool is connected to an impulse member 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/04",
    "title1": "•of the hammer piston type, i.e. in which the tool bit or anvil is hit by an impulse member 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/06",
    "title1": "•Means for driving the impulse member 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/08",
    "title1": "••comprising a built-in air compressor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/10",
    "title1": "••comprising a built-in internal-combustion engine 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/11",
    "title1": "••operated by combustion pressure generated by detonation of a cartridge 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/12",
    "title1": "••comprising a built-in liquid motor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/14",
    "title1": "•Control devices for the reciprocating piston 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/16",
    "title1": "••Valve arrangements therefor 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/18",
    "title1": "•••involving a piston-type slide valve 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/20",
    "title1": "•••involving a tubular-type slide valve 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/22",
    "title1": "•••involving a rotary-type slide valve 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/24",
    "title1": "•••involving a rocking-plate type valve 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 9/26",
    "title1": "••Control devices for adjusting the stroke of the piston or the force or frequency of impact thereof 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 11/00",
    "title1": "Portable percussive tools with electromotor drive (centrifugal or rotary impact type  B25D 15/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 11/02",
    "title1": "•in which the tool is connected to an impulse member 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 11/04",
    "title1": "•in which the tool bit or anvil is hit by an impulse member 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 11/06",
    "title1": "•Means for driving the impulse member 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 11/08",
    "title1": "••comprising a worm mechanism 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 11/10",
    "title1": "••comprising a cam mechanism 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 11/12",
    "title1": "••comprising a crank mechanism 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 13/00",
    "title1": "Portable percussive tools with electromagnetic drive (centrifugal or rotary impact type  B25D 15/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 15/00",
    "title1": "Portable percussive tools using centrifugal or rotary impact elements 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 15/02",
    "title1": "•in which the tool bit or anvil is hit by a rotary impulse member 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 16/00",
    "title1": "Portable percussive machines with superimposed rotation 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 16/00",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 17/00",
    "title1": "Details of, or accessories for, portable power-driven percussive tools 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/00",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 17/02",
    "title1": "•Percussive tool bits 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/02",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 17/04",
    "title1": "•Handles; Handle mountings 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/06",
    "title1": "•Hammer pistons; Anvils 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/08",
    "title1": "•Means for retaining and guiding the tool bit, e.g. chucks 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/10",
    "title1": "•Safety devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/10",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 17/11",
    "title1": "•Arrangements of noise damping means 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/11",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 17/12",
    "title1": "••of exhaust silencers 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/14",
    "title1": "•Removing or laying dust 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/14",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 17/16",
    "title1": "••by liquid 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/18",
    "title1": "••by exhausting dust-loaded air 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/20",
    "title1": "•Devices for cleaning or cooling tool or work 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/22",
    "title1": "••using pressure fluid 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/24",
    "title1": "•Damping the reaction force 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/26",
    "title1": "•Lubricating 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/26",
    "title1": "Definitions"
  },
  {
    "symbol": "B25D 17/28",
    "title1": "•Supports; Devices for holding power-driven percussive tools in working position 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/30",
    "title1": "••Pillars and struts 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25D 17/32",
    "title1": "••Trolleys 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
];