const resultB25C = [
  {
    "symbol": "B25C",
    "title1": "Warning: In this subclass, non-limiting references (in the sense of paragraph 39 of the Guide to the IPC) may still be displayed in the scheme."
  },
  {
    "symbol": "B25C 1/00",
    "title1": "Hand-held nailing tools (hammers  B25D; details or components, e.g. casings, bodies, of portable power-driven tools not particularly related to the operation performed  B25F 5/00; nailing machines  B27F 7/02); Nail feeding devices therefor 42006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/02",
    "title1": "•operated by manual power 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/04",
    "title1": "•operated by fluid pressure 32006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/06",
    "title1": "•operated by electric power 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/08",
    "title1": "•operated by combustion pressure 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/10",
    "title1": "••generated by detonation of a cartridge 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/12",
    "title1": "•••acting directly on the nail 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/14",
    "title1": "•••acting on an intermediate plunger or anvil (pistols for slaughtering or stunning animals  A22B 3/02) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/16",
    "title1": "•••Cartridges specially adapted for impact tools; Cartridge-and-nail units (bolts or the like for shooting into concrete constructions, metal walls, or the like by means of detonation-operated nailing tools  F16B 19/14) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 1/18",
    "title1": "•••Details or accessories, e.g. splinter guards, spall minimisers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 3/00",
    "title1": "Portable devices for holding and guiding nails; Nail dispensers 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/00",
    "title1": "Manually operated portable stapling tools; Hand-held power-operated stapling tools (surgical staplers  A61B 17/068,  A61B 17/115; details or components, e.g. casings, bodies, of portable power-driven tools not particularly related to the operation performed  B25F 5/00; stapling machines  B27F 7/17); Staple feeding devices therefor (surgical staples  A61B 17/064; staples  F16B 15/00) 3452006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/02",
    "title1": "•with provision for bending the ends of the staples on to the work 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/04",
    "title1": "••with means for forming the staples in the tool 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/06",
    "title1": "•without provision for bending the ends of the staples on to the work 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/08",
    "title1": "••with means for forming the staples in the tool 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/10",
    "title1": "•Driving means 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/11",
    "title1": "••operated by manual power 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/13",
    "title1": "••operated by fluid pressure 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/15",
    "title1": "••operated by electric power 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 5/16",
    "title1": "•Staple-feeding devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 7/00",
    "title1": "Accessories for nailing or stapling tools, e.g. supports (for tools operated by detonation of a cartridge  B25C 1/18) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 9/00",
    "title1": "Nail punches 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 11/00",
    "title1": "Nail, spike, or staple extractors (incorporated in hammers  B25D 1/00) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 11/02",
    "title1": "•Pincers (joints therefor  B25B 7/06) 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  },
  {
    "symbol": "B25C 13/00",
    "title1": "Nail straightening devices 2006.01\" href=\"#\" oncontextmenu=\"return false;\" onclick=\"return false;\">[2006.01]"
  }
];